name: 'build-and-push-to-gh'
description: 'build and push a docker image'
inputs:
  image-name: 
    description: 'name of the docker image'
    required: true
  registry:
    description: 'where to push image'
    default: ghcr.io
    required: false
  username:
    description: 'username to login to registry'
  password:
    description: 'token to login'
branding:
  icon: chevron-down
  color: gray-dark
#outputs:
#  text:
#    description: 'The text in lower case'
#    value: ${{ steps.lower-step.outputs.text }}
runs:
  using: "composite"
  steps:
    - name: login to registry
      run: |
        docker login ${{ inputs.registry }} -u ${{ inputs.username }} -p ${{ inputs.password }} 
      shell: bash

    - name: build image
      run: |
        docker build -t ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }} .
      shell: bash

    - name: push image
      run: |
        docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}
