on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test job build and push docker
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: login to registry
      uses: ./
      with:
        image-name: monimage
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
